<?php

namespace App\Model\Work\Entity\Projects\Role\Type;

use App\Model\Work\Entity\Projects\Role\Permission;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Types\JsonType;

class PermissionsType extends JsonType
{
    public const NAME = 'work_projects_role_permission';

    public function convertToDatabaseValue($value, AbstractPlatform $platform): ?string
    {
        if ($value instanceof ArrayCollection) {
            $data = array_map([self::class, 'deserialize'], $value->toArray());
        } else {
            $data = $value;
        }
        return parent::convertToDatabaseValue($data, $platform); // TODO: Change the autogenerated stub
    }

    public function convertToPHPValue($value, AbstractPlatform $platform)
    {
        $value = json_decode($value);
        if (!is_array($data = $value)) {
            return $data;
        }

        return new ArrayCollection(array_filter(array_map([self::class, 'serialize'], (array)$data)));
    }

    public function getName(): string
    {
        return self::NAME;
    }

    private static function deserialize(Permission $permission): string
    {
        return $permission->getName();
    }
    
    private static function serialize(string $name): ?Permission
    {
        return in_array($name, Permission::names(), true) ? new Permission($name) : null;
    }
}