doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_pgsql'
        server_version: '11.2'
        charset: utf8
        default_table_options:
            charset: utf8

        types:
            user_user_id: 'App\Model\User\Entity\User\Type\IdType'
            user_user_role: 'App\Model\User\Entity\User\Type\RoleType'
            user_user_email: 'App\Model\User\Entity\User\Type\EmailType'
            work_members_group_id: 'App\Model\Work\Entity\Members\Group\Type\IdType'
            work_members_member_id: 'App\Model\Work\Entity\Members\Member\Type\IdType'
            work_members_member_email: 'App\Model\Work\Entity\Members\Member\Type\EmailType'
            work_members_member_status: 'App\Model\Work\Entity\Members\Member\Type\StatusType'
            work_projects_project_id: 'App\Model\Work\Entity\Projects\Project\Type\IdType'
            work_projects_project_status: 'App\Model\Work\Entity\Projects\Project\Type\StatusType'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/User/Entity'
                prefix: 'App\Model\User\Entity'
                alias: User
            Work:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Model/Work/Entity'
                prefix: 'App\Model\Work\Entity'
                alias: Work


when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
